spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:mysql://localhost:3306/provasb_db?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: pass1
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          bytecode:
            use_reflection_optimizer: false # (se presente)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
